---
AWSTemplateFormatVersion: '2010-09-09'
Description: DNS Certs to live in us-east-1
Parameters:
  DomainName:
    Type: String
    Description: API Domain name
    Default: ''

  Route53HostedZone:
    Type: String
    Description: Hosted Zone
    Default: ''

Conditions:
  UseDomainName:
    !Not
      - !Equals
        - !Ref DomainName
        - ''

Resources:
  ISGApiCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Condition: UseDomainName
    Properties:
      ValidationMethod: DNS
      DomainName: !Sub '${DomainName}'
      DomainValidationOptions:
        - DomainName: !Sub '${DomainName}'
          HostedZoneId: !Ref Route53HostedZone
      SubjectAlternativeNames:
        - !Ref DomainName

Outputs:
  ISGApiCertificateARN:
    Value: !Ref ISGApiCertificate
    Description: ARN for certificate to be used for CloudFront static.